# Generated by Django 3.1.3 on 2021-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mens',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
